export enum BlogTMSReducerEnum {
  SET_BLOG_USERS_TMS = 'SET_BLOG_USERS_TMS',
  SET_BLOG_POSTS_TMS = 'SET_BLOG_POSTS_TMS',
  SET_SELECTED_BLOG_USER_ID_TMS = 'SET_SELECTED_BLOG_USER_ID_TMS',
  SET_COMMENTS_MODAL_STATUS_TMS = 'SET_COMMENTS_MODAL_STATUS_TMS',
  SET_IS_LOADING_STATUS_TMS = 'SET_IS_LOADING_STATUS_TMS',
  SET_SEARCH_STRING_TMS = 'SET_SEARCH_STRING_TMS',
  SET_COMMENTS_TMS = 'SET_COMMENTS_TMS',
  SET_ACTIVE_POST_TMS = 'SET_ACTIVE_POST_TMS',
}
